import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer — AstroVaanii" },
      {
        name: "description",
        content:
          "Disclaimer for AstroVaanii — understand the limitations of our astrological readings and AI-powered insights.",
      },
    ],
  }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-background grain">
      <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <Link
          to="/"
          className="text-primary hover:text-primary/80 mb-8 inline-block text-sm font-medium"
        >
          &larr; Back to Home
        </Link>
        <h1 className="text-primary mb-8 text-4xl font-bold">Disclaimer</h1>

        <div className="prose-custom space-y-6 text-sm leading-relaxed text-foreground/80">
          <p>
            The information and services provided by AstroVaanii (accessible at
            astrovaanii.com) are for general informational, educational, and
            entertainment purposes only. By using this website, you acknowledge
            and agree to the following disclaimers.
          </p>

          <h2 className="text-primary mt-8 text-xl font-semibold">
            Not Professional Advice
          </h2>
          <p>
            Astrological readings, horoscope interpretations, birth chart
            analyses, and any other content generated by AstroVaanii, including
            AI-powered responses, are not a substitute for professional advice.
            This includes but is not limited to medical, legal, financial,
            psychological, or any other professional advice. You should always
            consult a qualified professional for advice tailored to your
            specific circumstances.
          </p>

          <h2 className="text-primary mt-8 text-xl font-semibold">
            No Guarantees of Accuracy
          </h2>
          <p>
            While we strive to provide accurate and insightful astrological
            content based on classical principles, we make no representations or
            warranties of any kind, express or implied, regarding the accuracy,
            completeness, reliability, or suitability of the information
            provided. Astrology is an interpretive field and results may vary
            from person to person.
          </p>

          <h2 className="text-primary mt-8 text-xl font-semibold">
            Personal Responsibility
          </h2>
          <p>
            You are solely responsible for any decisions or actions you take
            based on the information provided by AstroVaanii. We shall not be
            held liable for any loss, damage, or injury arising from the use of
            this website or its content. By using this service, you agree to
            assume full responsibility for your own choices and outcomes.
          </p>

          <h2 className="text-primary mt-8 text-xl font-semibold">
            No Client-Astrologer Relationship
          </h2>
          <p>
            Use of AstroVaanii does not establish a client-astrologer
            relationship. The AI-generated readings are provided as a tool for
            self-reflection and should not be interpreted as personalized
            consultations with a human astrologer.
          </p>

          <h2 className="text-primary mt-8 text-xl font-semibold">
            External Links
          </h2>
          <p>
            This website may contain links to external websites. We do not
            endorse, control, or assume responsibility for the content,
            privacy policies, or practices of any third-party websites.
          </p>

          <h2 className="text-primary mt-8 text-xl font-semibold">
            Changes to This Disclaimer
          </h2>
          <p>
            We reserve the right to update or change this disclaimer at any
            time without prior notice. Changes will be effective immediately
            upon posting. We encourage you to review this page periodically
            for any updates.
          </p>

          <p className="mt-8 text-muted-foreground">
            If you have any questions about this disclaimer, please contact us
            through our website or reach out to our support team.
          </p>

          <p className="text-muted-foreground">
            Last updated: July 2026
          </p>
        </div>

        <div className="mt-16 border-t border-border pt-8">
          <div className="flex flex-wrap justify-center gap-x-8 gap-y-3 text-sm text-muted-foreground">
            <Link to="/" className="hover:text-foreground">Home</Link>
            <Link to="/privacy-policy" className="hover:text-foreground">Privacy Policy</Link>
            <Link to="/terms-and-conditions" className="hover:text-foreground">Terms &amp; Conditions</Link>
            <Link to="/refund-policy" className="hover:text-foreground">Refund Policy</Link>
            <span className="text-muted-foreground/50">Disclaimer</span>
          </div>
          <p className="mt-4 text-center text-xs text-muted-foreground/50">&copy; {new Date().getFullYear()} AstroVaanii</p>
        </div>
      </div>
    </main>
  );
}
